run: Linie.class Client.class Drive.class
	nxj -b -n NXT_07 -r Client
	nxj -b -n NXT_34 -r Client
	nxj -b -n IPS_05 -r Client

.SUFFIXES: .java .class

#Compiles from .java to .class
.java.class:
	nxjc *.java	
