run: Server.class Transporter.class
	java -cp "/home/nils/lejos_nxj/lib/pccomm.jar:/home/nils/lejos_nxj/3rdparty/lib/bluecove.jar:/home/nils/lejos_nxj/3rdparty/lib/bluecove-gpl.jar:." Server

.SUFFIXES: .java .class

#Compiles from .java to .class
.java.class:
	javac -cp "/home/nils/lejos_nxj/lib/pccomm.jar:/home/nils/lejos_nxj/3rdparty/lib/bluecove.jar:/home/nils/lejos_nxj/3rdparty/lib/bluecove-gpl.jar:." $*.java
